name: Sync Repo Metadata

on:
  push:
    branches: [master]
    paths:
      - "package.json"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-metadata:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract package.json info
        id: package-info
        run: |
          echo "description=$(jq -r '.description' package.json)" >> $GITHUB_OUTPUT
          echo "keywords=$(jq -c '.keywords' package.json)" >> $GITHUB_OUTPUT

      - name: Update Repository Description
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              description: '${{ steps.package-info.outputs.description }}'
            })

      - name: Update Repository Topics
        uses: actions/github-script@v7
        with:
          script: |
            const keywords = JSON.parse('${{ steps.package-info.outputs.keywords }}');
            github.rest.repos.replaceAllTopics({
              owner: context.repo.owner,
              repo: context.repo.repo,
              names: keywords.filter(word => word.length <= 35).slice(0, 20)
            })
